local p = require("fieldlights.palette")

return {

	pythonStatement = { fg = p.keyword, bold = true },
	pythonConditional = { fg = p.keyword },
	pythonDecorator = { fg = p.decorator },
	pythonInclude = { fg = p.keyword, bold = true },
	pythonOperator = { fg = p.keyword },
	pythonBuiltin = { fg = p.tokens },
	pythonPunctuation = { fg = p.decorator },
	["@operator"] = { fg = p.keyword },
	["@punctuation"] = { fg = p.fg },
	["@decorator"] = { fg = p.decorator },
	JavaScriptConditional = { fg = p.keyword },
	javaScriptException = { fg = p.keyword },
	javaScriptStatement = { fg = p.keyword },
	JavaScriptOperator = { fg = p.keyword },
	["@property.json"] = { fg = p.type },
	-- javaScriptParens   = { fg = p.decorator }, -- removed since adding rainbow-delimiter

	["@lsp.type.decorator"] = { fg = p.decorator },
	["@lsp.type.parameter.lua"] = { fg = p.tokens },
	["@lsp.typemod.parameter.declaration.lua"] = { fg = p.tokens },
	["@lsp.typemod.variable.definition.lua"] = { fg = p.type },
	["@lsp.typemod.variable.defaultLibrary.lua"] = { fg = p.tokens },
	["@lsp.typemod.class.defaultLibrary.javascript"] = { fg = p.function_name },
	["@lsp.typemod.member.defaultLibrary.javascript"] = { fg = p.function_name },
	["@variable.parameter.python"] = { fg = p.tokens },
	["@function.builtin.python"] = { fg = p.function_name },
	["@constant.builtin.python"] = { fg = p.tokens },
	["@attribute.python"] = { fg = p.func_name },
	JavaScriptNull = { fg = p.tokens },

	["@tag.delimiter.html"] = { fg = p.type },
	["@markup.heading.html"] = { fg = p.variable },
	["@markup.strong.html"] = { fg = p.variable },
	["@constant.html"] = { fg = p.type },
	["@tag.html"] = { fg = p.type },
	["@operator.html"] = { fg = p.type },
	["@tag.attribute.html"] = { fg = p.keyword },
	--["@nospell.html"] = { fg = p.type },
	["@variable.builtin.javascript"] = { fg = p.variable },

	-- Markdown
	markdownBold = { fg = p.markup_bold, bold = true },
	markdownItalic = { fg = p.markup_italic, italic = true },
	markdownUnderline = { fg = p.markup_underline, underline = true },
	markdownStrike = { fg = p.markup_strike, strikethrough = true },
	markdownBlockquote = { fg = p.markup_quote, italic = true },
	markdownCode = { fg = p.function_name, bg = p.bg2 },
	markdownHeading = { fg = p.string, bold = true },
	markdownLink = { fg = p.link, underline = true },
	markdownInserted = { fg = p.markup_inserted },
	markdownDeleted = { fg = p.markup_deleted },
	markdownChanged = { fg = p.markup_changed },

	-- tree-sitter-markdown
	["@markup.heading.1.markdown"] = { fg = p.string },
	["@markup.heading.2.markdown"] = { fg = p.string },
	["@markup.heading.3.markdown"] = { fg = p.string },
	["@markup.heading.4.markdown"] = { fg = p.string },
	["@markup.heading.5.markdown"] = { fg = p.string },
	["@markup.heading.6.markdown"] = { fg = p.string },
	["@_label.markdown_inline"] = { underline = false },
	["@markup.strong.markdown_inline"] = { fg = p.markup_bold, underline = false },
	["@markup.italic.markdown_inline"] = { fg = p.markup_bold },
	["@markup.raw.markdown_inline"] = { fg = p.markup_quote },
	["@markup.link.label.markdown_inline"] = { fg = p.markup_bold },
	["@markup.link.url.markdown_inline"] = { fg = p.markup_underline },
	["@markup.link.markdown_inline"] = { fg = p.variable },
	["@punctuation.special.markdown"] = { fg = p.comment },
	["@markup.raw.block.markdown"] = { fg = p.keyword },
	["@label.markdown"] = { fg = p.keyword },
	["@markup.list.markdown"] = { fg = p.variable },
	["@function.builtin.lua"] = { fg = p.function_name },

	-- JSON / AceJump / Decorator
	jsonKeyword = { fg = p.json_key },
	AceJumpBlue = { fg = p.fg, bg = p.acejump_blue },
	AceJumpGreen = { fg = p.fg, bg = p.acejump_green },
	AceJumpOrange = { fg = p.fg, bg = p.acejump_orange },
	AceJumpPurple = { fg = p.fg, bg = p.acejump_purple },
	Decorator = { fg = p.decorator, italic = true },

	-- Regex / URL
	Regex = { fg = p.regex },
	UnderlinedLink = { fg = p.link, underline = true },
}
