local p = require("fieldlights.palette")

return {
	-- Core syntax
	TSAnnotation = { fg = p.constant, italic = true },
	TSAttribute = { fg = p.type },
	TSBoolean = { fg = p.constant },
	TSCharacter = { fg = p.string },
	TSComment = { fg = p.comment, italic = true },
	TSConditional = { fg = p.keyword },
	TSConstant = { fg = p.constant },
	TSConstBuiltin = { fg = p.constant },
	TSConstMacro = { fg = p.constant },
	TSError = { fg = p.error },
	TSException = { fg = p.keyword },
	TSFloat = { fg = p.number },
	TSFunction = { fg = p.function_name },
	TSFuncBuiltin = { fg = p.function_name },
	TSFuncMacro = { fg = p.function_name },
	TSKeyword = { fg = p.keyword },
	TSKeywordFunction = { fg = p.function_name, italic = true },
	TSKeywordOperator = { fg = p.operator },
	TSKeywordImport = { fg = p.keyword },
	pythonStatement = { fg = p.keyword, bold = true },
	pythonConditional = { fg = p.keyword },
	pythonDecorator = { fg = p.decorator },
	pythonInclude = { fg = p.keyword, bold = true },
	pythonOperator = { fg = p.keyword },
	pythonBuiltin = { fg = p.tokens },
	pythonPunctuation = { fg = p.decorator },
	["@operator"] = { fg = p.keyword },
	["@punctuation"] = { fg = p.fg },
	["@decorator"] = { fg = p.decorator },
	JavaScriptConditional = { fg = p.keyword },
	javaScriptException = { fg = p.keyword },
	javaScriptStatement = { fg = p.keyword },
	JavaScriptOperator = { fg = p.keyword },
	["@property.json"] = { fg = p.type },
	-- javaScriptParens   = { fg = p.decorator }, -- removed since adding rainbow-delimiter
	TSLabel = { fg = p.type },
	TSMethod = { fg = p.function_name },
	TSNamespace = { fg = p.type },
	TSNumber = { fg = p.number },
	TSOperator = { fg = p.keyword },
	TSParameter = { fg = p.variable },
	TSParameterBuiltin = { fg = p.variable, italic = true },
	TSProperty = { fg = p.variable },
	TSPunctDelimiter = { fg = p.decorator },
	TSPunctBracket = { fg = p.decorator },
	TSPunctSpecial = { fg = p.comment },
	TSRepeat = { fg = p.keyword },
	TSString = { fg = p.string },
	TSStringEscape = { fg = p.constant },
	TSStringRegex = { fg = p.regex },
	TSSymbol = { fg = p.constant },
	TSTag = { fg = p.tag },
	TSTagAttribute = { fg = p.type, italic = true },
	TSText = { fg = p.fg },
	TSStrong = { fg = p.markup_bold, bold = true },
	TSEmphasis = { fg = p.markup_italic, italic = true },
	TSUnderline = { fg = p.markup_underline, underline = true },
	TSStrike = { fg = p.markup_strike, strikethrough = true },
	TSInserted = { fg = p.markup_inserted },
	TSDeleted = { fg = p.markup_deleted },
	TSChanged = { fg = p.markup_changed },
	TSKeywordReturn = { fg = p.keyword },
	TSFuncCall = { fg = p.function_name },
	TSVariable = { fg = p.variable },
	TSVariableBuiltin = { fg = p.constant, italic = true },
	TSDecorator = { fg = p.decorator, italic = true },

	-- Markdown (Treesitter)
	markdownBold = { fg = p.markup_bold, bold = true },
	markdownItalic = { fg = p.markup_italic, italic = true },
	markdownUnderline = { fg = p.markup_underline, underline = true },
	markdownStrike = { fg = p.markup_strike, strikethrough = true },
	markdownBlockquote = { fg = p.markup_quote, italic = true },
	markdownCode = { fg = p.function_name, bg = p.bg2 },
	markdownHeading = { fg = p.string, bold = true },
	markdownLink = { fg = p.link, underline = true },
	markdownInserted = { fg = p.markup_inserted },
	markdownDeleted = { fg = p.markup_deleted },
	markdownChanged = { fg = p.markup_changed },

	-- LSP
	DiagnosticError = { fg = p.error },
	DiagnosticWarn = { fg = p.warning },
	DiagnosticInfo = { fg = p.info },
	DiagnosticHint = { fg = p.type },
}
